// Generated by CoffeeScript 1.12.4
(function() {
  this.Thunk = (function() {
    function Thunk(prog, e) {
      if (!e) {
        this.v = prog;
        this.evaluated = true;
      } else {
        this.e = e;
        this.prog = prog;
        this.evaluated = false;
      }
    }

    Thunk.prototype["eval"] = function() {
      if (this.evaluated) {
        return this.v;
      }
      this.v = this.prog["eval"](this.e);
      this.evaluated = true;
      return this.v;
    };

    Thunk.prototype.asNum = function() {
      return this["eval"]().val;
    };

    Thunk.prototype.asFunc = function() {
      return this["eval"]();
    };

    Thunk.prototype.asMusic = function() {
      return this["eval"]();
    };

    return Thunk;

  })();

}).call(this);

//# sourceMappingURL=Thunk_N.js.map
