// Generated by CoffeeScript 1.12.4
(function() {
  var ConstVal, FunLVal, FunPVal, MusVal, createFunLValue, createFunPValue, createMusValue, createNumValue;

  ConstVal = (function() {
    function ConstVal(val) {
      this.val = val;
    }

    ConstVal.prototype.apply = function(t) {
      if (t) {
        thow('Cannot apply Constants');
      }
      return this.val;
    };

    return ConstVal;

  })();

  FunPVal = (function() {
    function FunPVal(n, fn) {
      if (typeof n === 'number') {
        this.n = n;
        this.fn = fn;
        this.args = [];
      } else {
        this.n = n.n;
        this.fn = n.fn;
        this.args = fn;
      }
    }

    FunPVal.prototype.apply = function(t) {
      var tempArgs;
      tempArgs = this.args.concat([t]);
      if (tempArgs.length === this.n) {
        return this.fn.apply(null, tempArgs);
      }
      return new FunPVal(this, tempArgs);
    };

    return FunPVal;

  })();

  FunLVal = (function() {
    function FunLVal(arg1, fn1, env1) {
      this.arg = arg1;
      this.fn = fn1;
      this.env = env1;
    }

    FunLVal.prototype.apply = function(t) {
      var envL;
      envL = new Env(this.arg.body, t, this.env);
      return this.fn["eval"](envL);
    };

    return FunLVal;

  })();

  MusVal = (function() {
    function MusVal(val) {
      this.val = val;
    }

    MusVal.prototype.apply = function(t) {
      if (t) {
        throw 'Cannot apply Musical values';
      }
      return this.val;
    };

    return MusVal;

  })();

  createNumValue = function(v) {
    throw 'Use Value.Const';
  };

  createFunPValue = function(n, fn) {
    throw 'Use Value.FunP';
  };

  createFunLValue = function(arg, fn, env) {
    throw 'Use Value.FunL';
  };

  createMusValue = function(v) {
    throw 'Use Value.Mus';
  };

  this.Value = {
    Const: ConstVal,
    Mus: MusVal,
    FunP: FunPVal,
    FunL: FunLVal
  };

}).call(this);

//# sourceMappingURL=Value.js.map
