// Generated by CoffeeScript 1.12.4
(function() {
  $(document).ready(function() {
    var n1, n2, s1, s2;
    n1 = new Note('alto_sax', 60, 100, 2);
    n2 = new Note('alto_sax', 60, 100, 2);
    s1 = new Seq(n1, n2);
    s2 = new Seq(n1, n2);
    s1.modInst('synth_drum');
    console.log(s1);
    return console.log(s2);
  });

}).call(this);

//# sourceMappingURL=testMusic.js.map
