// Generated by CoffeeScript 1.12.4
(function() {
  var input;

  input = splitByLine('15  2\n3.4');

  console.log(input);

  console.log(tokenize(input));

}).call(this);

//# sourceMappingURL=TokenizerTest.js.map
