// Generated by CoffeeScript 1.12.4
(function() {
  var input, test;

  test = 'func a:b =\n    3+b*a\n';

  input = splitByLine(test);

  console.log(input);

  console.log(tokenize(input));

}).call(this);

//# sourceMappingURL=TokenizerTest.js.map
